# Generated by Django 3.2.8 on 2021-10-23 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='productcompany',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='back_image',
            field=models.ImageField(upload_to='static/images/', verbose_name='Back Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_company', to='product.productcompany', verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_image',
            field=models.ImageField(upload_to='static/images/', verbose_name='Front Image'),
        ),
        migrations.AlterField(
            model_name='productcompany',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='productcompany',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='scientificcode',
            name='details',
            field=models.CharField(max_length=500, verbose_name='Details'),
        ),
    ]
