# Generated by Django 3.2.8 on 2021-10-27 03:10

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211023_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='back_image',
            field=models.ImageField(upload_to=product.models.get_upload_path, verbose_name='Back Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='front_image',
            field=models.ImageField(upload_to=product.models.get_upload_path, verbose_name='Front Image'),
        ),
        migrations.AlterField(
            model_name='scientificcode',
            name='details',
            field=models.TextField(max_length=500, verbose_name='Details'),
        ),
    ]
